name: 'Codeception Tests'
on:
  pull_request:
    paths:
      - 'common/src/**.php'
      - 'common/tests/**'
      - 'common/*.php'
      - 'src/**.php'
      - 'tests/**'
      - '*.php'
      - 'composer.json'
      - 'codeception.*.yml'
      - '.github/workflows/tests-php.yml'
jobs:
  test:
    strategy:
      matrix:
        fail-fast: 'false'
        suite:
          - unit
          - wpunit --skip-group="capacity"
          - wpunit --group="capacity"
          - integration
          - functional
          - restv1 --skip-group="capacity"
          - restv1 --group="capacity"
          - acceptance
          - views_integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout automation tools
        uses: actions/checkout@v2
        with:
          repository: moderntribe/tric
          ref: main
          path: tric
          fetch-depth: 1
      - name: Add tric to the PATH
        run: echo "::set-env name=PATH::${GITHUB_WORKSPACE}/tric:$PATH"
      - name: Set run_context() for tric
        run: echo "::set-env name=TRIC::1"
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "::set-env name=SSH_AUTH_SOCK::/tmp/ssh_agent.sock"
      - name: Set up tric for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          tric here
          tric interactive off
          tric build-prompt off
          tric xdebug off
          tric debug on
          tric info
      - name: Print the current tric configuration
        run: tric config
      - name: fetch and init TEC
        run: |
          cd ${GITHUB_WORKSPACE}/..
          git clone https://github.com/moderntribe/the-events-calendar.git
          cd the-events-calendar
          git checkout origin/release/B20.05
          sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
          git submodule update --init
          git submodule foreach --recursive "[ -f .gitmodules ] && sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules; git submodule update --init;"
          cd ${GITHUB_WORKSPACE}/..
          tric use the-events-calendar/common
          tric composer install --no-dev
          tric use the-events-calendar
          tric composer install --no-dev
      - name: Set up event-tickets
        run: |
          tric use event-tickets
          tric composer install
      - name: Init the WordPress container
        run: tric up wordpress
      - name: Run suite tests
        run: tric run ${{ matrix.suite }}
